=== acionescu/netcell-gui/src/main/resources/dtds/ui-generator.dtd
<!ELEMENT descriptions (class-desc*) >

<!ELEMENT class-desc (field-desc*, list-field-desc*, map-field-desc* )* >
<!ATTLIST class-desc id CDATA #REQUIRED >

<!ELEMENT field-desc EMPTY >
<!ATTLIST field-desc name CDATA #REQUIRED >
<!ATTLIST field-desc label CDATA #IMPLIED >
<!ATTLIST field-desc type CDATA #IMPLIED >
<!ATTLIST field-desc source CDATA #IMPLIED >
<!ATTLIST field-desc editable (true | false) #IMPLIED >
<!ATTLIST field-desc nested-type CDATA #IMPLIED >

<!ELEMENT list-field-desc EMPTY>
<!ATTLIST list-field-desc name CDATA #REQUIRED >
<!ATTLIST list-field-desc label CDATA #IMPLIED >
<!ATTLIST list-field-desc type CDATA #IMPLIED >
<!ATTLIST list-field-desc source CDATA #IMPLIED >
<!ATTLIST list-field-desc editable (true | false) #IMPLIED >
<!ATTLIST list-field-desc nested-type CDATA #IMPLIED >

<!ELEMENT map-field-desc (key-field-desc?, value-field-desc?) >
<!ATTLIST map-field-desc name CDATA #REQUIRED >
<!ATTLIST map-field-desc editable (true | false) #IMPLIED >
<!ATTLIST map-field-desc label CDATA #IMPLIED >

<!ELEMENT key-field-desc (field-desc?, list-field-desc?, map-field-desc?) >

<!ELEMENT value-field-desc (field-desc?, list-field-desc?, map-field-desc?) >

=== acionescu/netcell-gui/src/main/resources/xmls/ui-config-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    netcell-gui - A Swing GUI for netcell ESB
    Copyright (C) 2009  Adrian Cristian Ionescu - https://github.com/acionescu

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!DOCTYPE descriptions SYSTEM "../dtds/ui-generator.dtd">


<descriptions>

	<class-desc id="net.segoia.netcell.vo.definitions.WorkFlowDefinition">
		<field-desc name="id" type="TEXTFIELD" />
		<list-field-desc name="inputParameters" nested-type="net.segoia.netcell.vo.InputParameter" />
		<list-field-desc name="outputParameters" editable="false"
			nested-type="net.segoia.netcell.vo.OutputParameter" />
	</class-desc>

	<class-desc id="net.segoia.netcell.vo.InputParameter">
		<field-desc name="name" type="TEXTFIELD" />
		<field-desc name="value" type="TEXTFIELD" />
		<field-desc name="type" type="COMBOBOX" source="types" />
		<field-desc name="mandatory" type="CHECKBOX" />
	</class-desc>

	<class-desc id="net.segoia.netcell.vo.OutputParameter">
		<field-desc name="name" type="TEXTFIELD" />
		<field-desc name="value" type="TEXTFIELD" />
		<field-desc name="type" type="COMBOBOX" source="types" />
		<field-desc name="mandatory" type="CHECKBOX" />
	</class-desc>
	
	<class-desc id="net.segoia.netcell.vo.configurations.WorkFlowComponentConfiguration">
		<field-desc name="localId" type="TEXTFIELD"/>
		<map-field-desc name="outputParamsMappings" editable="true">
			<key-field-desc>
				<field-desc name="key" source="availableParameters" type="COMBOBOX"/>
			</key-field-desc>
			<value-field-desc>
				<field-desc name="value" type="TEXTFIELD" nested-type="java.lang.String"/>
			</value-field-desc>
			
		</map-field-desc>
	</class-desc>
	
	<class-desc id="net.segoia.netcell.vo.configurations.ComponentConfiguration">
	
	</class-desc>

</descriptions>
